#config_version=6
mode:
  start_events: ball_starting
  priority: 101
  
shots:


  r_captive_l_div:
    switch: s_captive_l

   
   
variable_player:
    mode_diverter_activation_started:
     v_right_ramp:
       int: 0
       action: set

    r_captive_l_div_hit:
      v_right_ramp: 1
      
    diverter_activate:
      v_right_ramp:
       int: 0
       action: set
  
event_player:

  r_captive_l_div_hit:  diverter_activate

timers:
  t_diverter_reactivate:
    start_value: 16
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - event: diverter_d_middle_diverter_activating
        action: start
      - event: timer_t_diverter_reactivate_complete
        action: stop
      - event: timer_t_diverter_reactivate_complete
        action: reset
    start_running: false
    