#config_version=6

show_player:
  mode_attract_started: attract_lcd
  mode_attract_started.1: attract_gi

  
slide_player:
  mode_attract_started:
    base:
      action: remove
  mode_attract_ending:
    attract_fast:
      action: remove
    attract:
      action: remove
    base:
      action: queue_immediate