#config_version=6

  
hardware:
  platform: fast

playfields:
  playfield:
    default_source_device: bd_autolauncher
    tags: default 


fast:
  net:
    port: com3
    controller: neuron
    io_loop:
      b_cabinet:
        model: FP-I/O-0804
        order: 1
      b_lower_mini:
        model: FP-I/O-0804
        order: 2
      b_main:
        model: FP-I/O-3208
        order: 3
      b_middle:
        model: FP-I/O-1616
        order: 4
      b_back:
        model: FP-I/O-3208
        order: 5
        

    

modes:



    
lights:







  
    
coils:

# Board 1 - Cabinet

  c_shaker:
    number: b_cabinet-0
    default_pulse_ms: 1
    default_hold_power: 0.125
    
# Board 2 - Lower Mini


  c_flipper_lower_l:
    number: b_lower_mini-1
    default_pulse_ms: 20
    allow_enable: true
    default_hold_power: 1
    
  c_flipper_lower_r:
    number: b_lower_mini-2
    default_pulse_ms: 20
    allow_enable: true
    default_hold_power: 1
    
  c_sling_lower:
    number: b_lower_mini-3
    default_pulse_ms: 10

  c_lower_vuk:
    number: b_lower_mini-0
    default_pulse_ms: 30


# Board 3 - Main

  c_trough:
    number: b_main-0
    default_pulse_ms: 10
    default_pulse_power: 1
    
  c_autolauncher:
    number: b_main-1
    default_pulse_ms: 15
    default_pulse_power: 1
    allow_enable: true
    default_hold_power: 1

    
  c_flipper_l_main:
    number: b_main-2
    default_pulse_ms: 30
    default_hold_power: 1
  c_flipper_l_hold:
    number: b_main-3
    default_pulse_ms: 20
    allow_enable: true
    default_hold_power: 1
    
  c_flipper_r_main:
    number: b_main-4
    default_pulse_ms: 50
    allow_enable: true
    default_hold_power: 1 
  c_flipper_r_hold:
    number: b_main-5
    default_pulse_ms: 20
    allow_enable: true
    default_hold_power: 1
    


  c_kicking_target:
    number: b_middle-7
    default_pulse_ms: 10
    default_pulse_power: 1
    default_recycle: true
  c_pop:
    number: b_main-7
    default_pulse_ms: 8
    

    
# Board 4 - Middle

  c_flipper_l_upper_main:
    number: b_middle-9
    allow_enable: true
    default_hold_power: 1
    default_pulse_power: 1
    default_pulse_ms: 30

  c_flipper_l_upper_hold:
    number: b_middle-8
    default_pulse_ms: 20
    allow_enable: true
    default_hold_power: 1
    default_pulse_power: 1
    
  c_inlane_post:
    number: b_middle-10
    allow_enable: true
    default_hold_power: 0.25
    default_pulse_power: 1
    default_pulse_ms: 10
    
  c_sling_l:
    number: b_middle-11
    default_pulse_power: 1
    default_pulse_ms: 15
    
  c_drop_reset:
    number: b_middle-14
    default_pulse_power: 1
    default_pulse_ms: 12
  c_drop_release:
    number: b_middle-12
    default_pulse_power: 0.75
    default_pulse_ms: 10
    
  c_kicker_orbit:
    number: b_middle-15
    default_pulse_power: 1
    default_pulse_ms: 20
    
    
  c_middle_scoop:
    number: b_middle-2
    default_pulse_power: 1
    default_pulse_ms: 20
    

  c_drop_single:
    number: b_middle-1
    default_pulse_power: 0.75
    default_pulse_ms: 60
  c_drop_single_release:
    number: b_middle-0
    default_pulse_power: 0.75
    default_pulse_ms: 20
    
# Board 5 - Back + Upper

  c_vuk_back:
   number: b_back-5
   default_pulse_ms: 30
   default_pulse_power: 1


  c_b_flipper_main:
    number: b_back-3
    default_pulse_power: 1
    default_pulse_ms: 20
  c_b_flipper_hold:
    number: b_back-4
    allow_enable: true
    default_hold_power: 1
    
  c_b_lock:
    number: b_back-1
    allow_enable: true
    default_pulse_power: 0.7
    default_pulse_ms: 100
    
  c_b_pop:
    number: b_back-2
    default_pulse_ms: 20
    
  c_u_flipper:
    number: b_back-0
    allow_enable: true
    default_hold_power: 0.5
    
  c_vuk_upper:
    number: b_back-7
    default_pulse_power: 1
    default_pulse_ms: 30
    
switches:


  s_flipper_but_r_1:
    number: b_cabinet-0
  s_flipper_but_r_2:
    number: b_cabinet-1
  s_flipper_but_l_1:
    number: b_cabinet-2
  s_flipper_but_l_2:
    number: b_cabinet-3
  s_launch:
    number: b_cabinet-4
    tags: launch
  s_tilt:
    number: b_cabinet-5
    tags: tilt
  s_start:
    number: b_cabinet-6
    tags: start

  s_bot:
    number:  b_lower_mini-0
  s_lower_single:
    number:  b_lower_mini-1
  s_lower_sling:
    number:  b_lower_mini-2
  s_bot_mid:
    number:  b_lower_mini-3
  s_top_mid:
    number:  b_lower_mini-4
  s_lower_orbit:
    number:  b_lower_mini-5
    type: 'NC'
  s_top:
    number:  b_lower_mini-6
  s_lower_vuk:
    number:  b_lower_mini-7
    type: 'NC'


  s_outlane_l:
    number: b_main-0
    type: 'NC'
  s_inlane_l:
    number: b_main-1
    type: 'NC'
    
  s_outlane_r:
    number: b_main-6
    type: 'NC'
  s_inlane_r:
    number: b_main-7
    type: 'NC'

  s_trough_6:
    number: b_main-8
    type: 'NC'
  s_trough_5:
    number: b_main-9
    type: 'NC'
  s_trough_4:
    number: b_main-10
    type: 'NC'
  s_trough_3:
    number: b_main-11
    type: 'NC'
  s_trough_2:
    number: b_main-12
    type: 'NC'
  s_trough_1:
    number: b_main-14
    type: 'NC'
  s_trough_jam:
    number: b_main-15
    type: 'NC'
    
  s_flipper_l:
    number: b_main-16
    type: 'NC'
  s_lower_transfer:
    number: b_main-17
  s_flipper_r:
    number: b_main-18
    type: 'NC'
  s_flipper_upper_l:
    number: b_main-19
    type: 'NC'
  s_pop:
    number: b_main-20
  s_kicking_target:
    number: b_main-21
  s_autolauncher:
    number: b_main-22
  s_scissor_save:
    number: b_main-23
    
  s_kicker_orbit:
    number: b_middle-0
    type: 'NC'
  s_drop_r:
    number: b_middle-1
  s_drop_m:
    number: b_middle-2
  s_drop_l:
    number: b_middle-3
  s_subway:
    number: b_middle-4
    type: 'NC'
  s_stationary_l:
    number: b_middle-5
  s_sling_l:
    number: b_middle-6
  s_stationary_m:
    number: b_middle-7
    
  s_orbit_small_r:
    number: b_middle-8
  s_drop_single:
    number: b_middle-9
    type: 'NC'
  s_orbit_small_l:
    number: b_middle-10
  s_middle_scoop:
    number: b_middle-11
    type: 'NC'
  s_stationary_r:
    number: b_middle-12
  s_captive_r:
    number: b_middle-13
  s_captive_l:
    number: b_middle-14
    
    
# Board 4 - Back + Upper

  s_vuk_back:
    number: b_back-2
    type: 'NC'
  s_b_rollover_loop:
    number: b_back-3
  s_b_rollover_misc:
    number: b_back-4
  s_b_eos:
    number: b_back-0
    type: 'NC'
  s_b_pop:
    number: b_back-1
  s_b_target_right:
    number: b_back-6
  s_b_target_left:
    number: b_back-7
  s_b_rollover_interchange:
    number: b_back-5
    
  s_lock_1:
    number: b_back-24
    type: 'NC'
  s_lock_2:
    number: b_back-25
    type: 'NC'
  s_lock_3:
    number: b_back-26
    type: 'NC'
    
  s_vuk_upper:
    number: b_back-27
    type: 'NC'
    
  s_u_rollover:
    number: b_back-8
  s_u_target:
    number: b_back-9
  s_u_lane_r:
    number: b_back-10
  s_u_lane_l:
    number: b_back-11
    
ball_devices:

  bd_middle_scoop:
    ball_switches: s_middle_scoop
    eject_coil: c_middle_scoop
    eject_timeouts: 1s
    
  bd_trough:
  # s_trough_6, s_trough_5, s_trough_4, s_trough_3, s_trough_2, 
    ball_switches: s_trough_1
    eject_coil: c_trough
    eject_timeouts: 1s
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_autolauncher
    
  bd_autolauncher:
    ball_switches: s_autolauncher
    entrance_count_delay: 300ms
    eject_timeouts: 3s
    eject_coil: c_autolauncher
    player_controlled_eject_event: sw_launch
    
  bd_kicker_orbit:
    ball_switches: s_kicker_orbit
    eject_coil: c_kicker_orbit
    eject_timeouts: 1s
    
    
  bd_lower_vuk:
    ball_switches: s_lower_vuk
    eject_coil: c_lower_vuk
    eject_timeouts: 1s
    
  bd_vuk_back:
    ball_switches: s_vuk_back
    eject_coil: c_vuk_back
    eject_timeouts: 2s
    
  bd_vuk_upper:
    ball_switches: s_vuk_upper
    eject_coil: c_vuk_upper
    eject_timeouts: 2s
    
  bd_b_lock:
    ball_switches: s_lock_1, s_lock_1, s_lock_1
    eject_coil: c_b_lock
    eject_timeouts: 2s
    
flippers:

  f_l:
    main_coil: c_flipper_l_main
    hold_coil: c_flipper_l_hold
    activation_switch: s_flipper_but_l_1
    eos_switch: s_flipper_l
    enable_events: ball_started
    
  f_l_upper:
    main_coil: c_flipper_l_upper_main
    hold_coil: c_flipper_l_upper_hold
    activation_switch: s_flipper_but_l_1
    eos_switch: s_flipper_l
    enable_events: ball_started
    
  f_r:
    main_coil: c_flipper_r_main
    hold_coil: c_flipper_r_hold
    activation_switch: s_flipper_but_r_1
    #eos_switch: s_flipper_upper_l
    enable_events: ball_started
    
  f_lower_r:
    main_coil: c_flipper_lower_r
    activation_switch: s_flipper_but_r_2
    enable_events: lower_flippers_enable
    disable_events: ball_started
  f_lower_l:
    main_coil: c_flipper_lower_l
    activation_switch: s_flipper_but_l_2
    enable_events: lower_flippers_enable
    disable_events: ball_started
    
    
  f_back:
    main_coil: c_b_flipper_main
    hold_coil: c_b_flipper_hold
    activation_switch: s_flipper_but_r_2
    
  f_upper:
    main_coil: c_u_flipper
    activation_switch: s_flipper_but_l_2
    
drop_targets:
    d_drop_single:
      switch: s_drop_single
      knockdown_coil: c_drop_single_release
      


      

    right:
      switch: s_drop_r

    mid:
      switch: s_drop_m

    left:
      switch: s_drop_l

drop_target_banks:

    dt_single:
      drop_targets: d_drop_single
      reset_coil: c_drop_single
      reset_events: ball_started
     #   balldevice_bd_top_vuk_eject_success: 0.25s
      #  s_pop_right_hit: 0.25s
       # ball_started: 0s
      reset_on_complete: 10s
      

      
      
    mid:
      drop_targets:  left, right, mid
      reset_coil: c_drop_reset
      reset_events: ball_started
    
    
autofire_coils:

  ac_pop:
    coil: c_pop
    switch: s_pop
  
  ac_kicking_target:
    coil: c_kicking_target
    switch: s_kicking_target
  
  ac_sling_l:
    coil: c_sling_l
    switch: s_sling_l
    
  ac_sling_lower:
    coil: c_sling_lower
    switch: s_lower_sling
    
  ac_pop_back:
    coil: c_b_pop
    switch: s_b_pop
    
