#config_version=6

modes:

  - base
  - base_gi_control
  - base_upper_trash_spell
  - base_vertical_ball1_flip
  - attract
  - diverter_activation

  - misc_drop_bank
  - misc_drop_bank_lit
  - misc_launch_shows