#config_version=6

config:
    - config_lights.yaml
    - config_modes.yaml
    - config_fast.yaml
    - config_coils.yaml
    - config_switches.yaml
    - config_devices.yaml
    - config_misc.yaml
    - config_player_vars.yaml
    
    
  
mpf:
  report_crashes: never

    
 

    
